export const tools = [
    { name: 'Advanced Suite', icon: '⚡', href: '/nfc-tool', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Read, write, clone, format & lock' },
    { name: 'Read NFC', icon: '📖', href: '/read-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Scan any tag & inspect records' },
    { name: 'Write NFC', icon: '✍️', href: '/write-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Program custom text, URLs & vCards' },
    { name: 'Clone NFC', icon: '📋', href: '/clone-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Duplicate NDEF messages between tags' },
    { name: 'Erase NFC', icon: '🗑️', href: '/erase-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Wipe all records from an NFC tag' },
    { name: 'Format NFC', icon: '🛠️', href: '/format-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Initialize NDEF tag memory structure' },
    { name: 'Lock NFC', icon: '🔒', href: '/lock-nfc', category: 'nfc-hardware', badge: 'NFC Only', hasNfc: true, hasQr: false, desc: 'Make tag permanently read-only' },
    { name: 'vCard', icon: '📇', href: '/vcard', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Digital contact card · QR & NFC tag' },
    { name: 'UPI Pay', icon: '💳', href: '/upi', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Instant tap-to-pay QR & NFC tag' },
    { name: 'URL QR', icon: '🔗', href: '/url', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Website links · QR code & NFC tag' },
    { name: 'WiFi QR', icon: '📶', href: '/wifi', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Tap or scan to connect to WiFi' },
    { name: 'SMS QR', icon: '💬', href: '/sms', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Pre-filled text messages · QR & NFC' },
    { name: 'Email QR', icon: '✉️', href: '/email', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Pre-filled email drafts · QR & NFC' },
    { name: 'Call QR', icon: '📞', href: '/call', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'Instant one-tap dialer · QR & NFC' },
    { name: 'Event QR', icon: '📅', href: '/event', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'vEvent calendar invites · QR & NFC' },
    { name: 'Location QR', icon: '📍', href: '/location', category: 'nfc-qr', badge: 'NFC + QR', hasNfc: true, hasQr: true, desc: 'GPS & DigiPin navigation · QR & NFC' },
    { name: 'QR Tools', icon: '🔳', href: '/qr', category: 'qr-hub', badge: 'QR Hub', hasNfc: true, hasQr: true, desc: 'Overview of all QR + NFC generators' },
];